server:
  port: 8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce?currentSchema=orders
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: orders

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: orders

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration-ms: 86400000

services:
  stock:
    url: ${SERVICES_STOCK_URL:http://localhost:8084}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs