server:
  port: ${PORT:8083}

grpc:
  server:
    port: ${GRPC_PORT:9090}
    reflection:
      enabled: true

spring:
  application:
    name: product-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 10

  jackson:
    serialization:
      write-dates-as-timestamps: false   # LocalDateTime → ISO-8601 string (JSON cache deserialize için gerekli)

  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce?currentSchema=products
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

# Auth Service ile AYNI secret olmalı
jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
